on: push
name: Push
jobs:
  test1:
    name: Unit Test Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y exiftool 
    - name: Run Test
      run: ./test/run.sh 
  test2:
    name: Unit Test MacOSX
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: brew install exiftool 
    - name: Run Test
      run: ./test/run.sh 
