on: push
name: Push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y exiftool 
    - name: Test
      uses: skx/github-action-tester@master
