on: push
name: Ubuntu
jobs:
  test1:
    name: Unit Test Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y exiftool 
    - name: Run Test
      run: ./test/run.sh 
